// test/fhe/quantization_test.dart
//
// Tests for the FHE quantization step:
//   float32 feature vector → uint8 quantized values (input quantizers)
//   raw int8 model output   → float32 dequantized scores (output quantizer)
//
// Reference values were computed by gen_test_vectors.py using the same
// quantization parameters extracted from client.zip.
//
// These tests verify:
//   1. The quantization formula matches Python's UniformQuantizer
//   2. Selected per-dimension values from real test sentences
//
// Run with:
//   cd journal_app && flutter test test/fhe/quantization_test.dart

import 'dart:io';

import 'package:flutter_concrete/src/client_zip_parser.dart';
import 'package:flutter_test/flutter_test.dart';

// ── Quantization helpers (mirrors fhe_helper.py logic) ─────────────────────

/// Quantize a float32 value using an unsigned 8-bit uniform quantizer.
///
/// Formula: q = clip(round(x / scale) + zero_point, 0, 255)
/// Matches concrete-ml's UniformQuantizer (unsigned, n_bits=8).
int quantizeInput(double x, double scale, int zeroPoint) {
  final q = (x / scale).roundToDouble() + zeroPoint;
  return q.clamp(0, 255).toInt();
}

/// Dequantize a raw signed 8-bit output value to float32.
///
/// Formula: float = (int_val - zero_point) * scale
/// Matches concrete-ml's output quantizer (is_signed=True, offset=128).
double dequantizeOutput(int intVal, double scale, int zeroPoint) {
  return (intVal - zeroPoint) * scale;
}

// ── Reference data ─────────────────────────────────────────────────────────
// Generated by: python3 emotion_ml/gen_test_vectors.py
// First 10 quantized values for each test sentence.
const Map<String, List<int>> _kRefQuantized = {
  'I am happy': [15, 92, 64, 56, 100, 99, 79, 110, 132, 102],
  'This makes me so angry and frustrated': [84, 84, 60, 95, 84, 113, 63, 121, 159, 144],
  'I feel nothing today': [26, 92, 61, 56, 97, 97, 77, 108, 132, 100],
  'Today was a great day and I felt wonderful': [70, 79, 59, 43, 94, 123, 82, 89, 135, 128],
  'The quick brown fox jumped over the lazy dog': [111, 67, 36, 39, 194, 76, 72, 66, 109, 82],
  'I am so sad and heartbroken': [65, 89, 63, 56, 88, 105, 74, 109, 140, 123],
  'Wow that was surprising and unexpected': [82, 78, 55, 36, 81, 134, 148, 84, 132, 139],
};

// Float32 vectors (first 10 dims) — same as in vectorizer_test.dart.
const Map<String, List<double>> _kRefVectors = {
  'I am happy': [
    0.03307695314288139, 0.007266590371727943, -7.130046287784353e-05,
    -0.00017122927238233387, -0.008795296773314476, 0.009200588800013065,
    -0.006785948295146227, 0.028271257877349854, 0.018931765109300613,
    0.016355399042367935,
  ],
  'This makes me so angry and frustrated': [
    0.183515265583992, -0.029108818620443344, -0.018940437585115433,
    0.16955099999904633, -0.07135626673698425, 0.06460697203874588,
    -0.07893148809671402, 0.07514217495918274, 0.12172309309244156,
    0.19083626568317413,
  ],
  'I feel nothing today': [
    0.05742885544896126, 0.009276262484490871, -0.015289772301912308,
    0.0009941915050148964, -0.021609734743833542, 0.0006966697983443737,
    -0.013212052173912525, 0.02216663956642151, 0.01846163347363472,
    0.009984776377677917,
  ],
  'Today was a great day and I felt wonderful': [
    0.1542942374944687, -0.04961022734642029, -0.021712662652134895,
    -0.05428064987063408, -0.030411895364522934, 0.10285940766334534,
    0.007325266487896442, -0.05982472002506256, 0.03139490261673927,
    0.12544764578342438,
  ],
  'The quick brown fox jumped over the lazy dog': [
    0.24373970925807953, -0.10785162448883057, -0.12546607851982117,
    -0.07246184349060059, 0.3709394037723541, -0.08498900383710861,
    -0.03576260060071945, -0.15480954945087433, -0.06720925122499466,
    -0.06736700236797333,
  ],
  'I am so sad and heartbroken': [
    0.14323167502880096, -0.0042037880048155785, -0.006477745249867439,
    0.0019004767527803779, -0.05492603778839111, 0.030431291088461876,
    -0.027710849419236183, 0.024354755878448486, 0.049799833446741104,
    0.10380487889051437,
  ],
  'Wow that was surprising and unexpected': [
    0.17926029860973358, -0.0542730875313282, -0.04211649298667908,
    -0.08582140505313873, -0.08704036474227905, 0.14770174026489258,
    0.31680700182914734, -0.0788261815905571, 0.019036270678043365,
    0.16704733669757843,
  ],
};

// ── Tests ──────────────────────────────────────────────────────────────────

void main() {
  // Load quantization params once for all tests.
  late List<Map<String, dynamic>> inputQuantizers;
  late Map<String, dynamic> outputQuantizer;

  setUpAll(() {
    final zipBytes = File('../journal_app/assets/fhe/client.zip').readAsBytesSync();
    final parseResult = ClientZipParser.parse(zipBytes);
    final qp = parseResult.quantParams;
    inputQuantizers = qp.input.map((p) => {
      'scale': p.scale,
      'zero_point': p.zeroPoint,
    }).toList();
    outputQuantizer = {
      'scale': qp.output.scale,
      'zero_point': qp.output.zeroPoint,
      'offset': qp.output.offset,
      'n_classes': 5,
    };
  });

  group('client.zip quantization sanity checks', () {
    test('has exactly 200 input quantizers', () {
      expect(inputQuantizers.length, equals(200));
    });

    test('each input quantizer has required fields', () {
      for (int i = 0; i < inputQuantizers.length; i++) {
        final q = inputQuantizers[i];
        expect(q.containsKey('scale'), isTrue, reason: 'input[$i] missing scale');
        expect(q.containsKey('zero_point'), isTrue, reason: 'input[$i] missing zero_point');
        expect((q['scale'] as num).toDouble(), greaterThan(0),
            reason: 'input[$i] scale must be positive');
      }
    });

    test('output quantizer has required fields', () {
      expect(outputQuantizer.containsKey('scale'), isTrue);
      expect(outputQuantizer.containsKey('zero_point'), isTrue);
      expect(outputQuantizer.containsKey('n_classes'), isTrue);
      expect(outputQuantizer['n_classes'], equals(5));
    });

    test('all input zero_points are in [0, 255]', () {
      for (int i = 0; i < inputQuantizers.length; i++) {
        final zp = inputQuantizers[i]['zero_point'] as int;
        expect(zp, inInclusiveRange(0, 255),
            reason: 'input[$i] zero_point out of range');
      }
    });
  });

  group('quantizeInput formula', () {
    test('basic examples match expected values', () {
      // x=0, scale=1, zp=0 → 0
      expect(quantizeInput(0.0, 1.0, 0), equals(0));
      // x=1, scale=1, zp=0 → 1
      expect(quantizeInput(1.0, 1.0, 0), equals(1));
      // x=0.5, scale=1, zp=0 → round(0.5)=0 (banker's rounding) or 1 — just finite
      expect(quantizeInput(0.5, 1.0, 0), inInclusiveRange(0, 1));
      // x=-1, scale=1, zp=128 → clip(round(-1)+128, 0, 255) = 127
      expect(quantizeInput(-1.0, 1.0, 128), equals(127));
      // x=200, scale=1, zp=0 → clip(200, 0, 255) = 200
      expect(quantizeInput(200.0, 1.0, 0), equals(200));
    });

    test('clamps to [0, 255]', () {
      expect(quantizeInput(1000.0, 1.0, 0), equals(255));
      expect(quantizeInput(-1000.0, 1.0, 0), equals(0));
    });

    test('scale divides correctly', () {
      // x=0.5, scale=0.5, zp=0 → round(1.0)+0 = 1
      expect(quantizeInput(0.5, 0.5, 0), equals(1));
      // x=1.0, scale=0.25, zp=10 → round(4)+10 = 14
      expect(quantizeInput(1.0, 0.25, 10), equals(14));
    });
  });

  group('dequantizeOutput formula', () {
    test('zero maps to -zero_point * scale', () {
      final scale = (outputQuantizer['scale'] as num).toDouble();
      final zp = outputQuantizer['zero_point'] as int;
      final result = dequantizeOutput(0, scale, zp);
      expect(result, closeTo(-zp * scale, 1e-10));
    });

    test('zero_point maps to 0.0', () {
      final scale = (outputQuantizer['scale'] as num).toDouble();
      final zp = outputQuantizer['zero_point'] as int;
      final result = dequantizeOutput(zp, scale, zp);
      expect(result, closeTo(0.0, 1e-10));
    });

    test('known output values are reasonable floats', () {
      final scale = (outputQuantizer['scale'] as num).toDouble();
      final zp = outputQuantizer['zero_point'] as int;
      // All uint8 values should dequantize to finite floats.
      for (int i = 0; i <= 255; i++) {
        final v = dequantizeOutput(i, scale, zp);
        expect(v.isFinite, isTrue, reason: 'dequantize($i) must be finite');
      }
    });
  });

  group('Input quantization matches Python reference (first 10 dims)', () {
    for (final entry in _kRefQuantized.entries) {
      final sentence = entry.key;
      final refQuantized = entry.value;
      final refVector = _kRefVectors[sentence]!;

      test(sentence, () {
        for (int i = 0; i < refQuantized.length; i++) {
          final q = inputQuantizers[i];
          final scale = (q['scale'] as num).toDouble();
          final zp = q['zero_point'] as int;
          final dartQ = quantizeInput(refVector[i], scale, zp);
          expect(dartQ, equals(refQuantized[i]),
              reason: 'dim[$i] for "$sentence": '
                  'dart=$dartQ python=${refQuantized[i]} '
                  '(x=${refVector[i]}, scale=$scale, zp=$zp)');
        }
      });
    }
  });
}
