// test/fhe/vectorizer_test.dart
//
// Regression tests for the pure-Dart TF-IDF + LSA + L2-normalize pipeline.
//
// Reference values were computed by the Python pipeline using the same trained
// artifacts (vocab.json, idf_weights.bin, svd_components.bin) via:
//
//   python3 emotion_ml/gen_test_vectors.py
//
// The test checks that Dart output matches Python output within float32
// rounding tolerance (≤ 2e-4 absolute, or ≤ 1% relative for larger values).
//
// Run with:
//   cd journal_app && flutter test test/fhe/vectorizer_test.dart

import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:journal_app/fhe/vectorizer.dart';

// ── Reference data ─────────────────────────────────────────────────────────
// Generated by: python3 emotion_ml/gen_test_vectors.py
// Format: { sentence: [v0, v1, ..., v9] }  — first 10 of 200 dims.
const Map<String, List<double>> _kRefVectors = {
  'I am happy': [
    0.03307695314288139,
    0.007266590371727943,
    -7.130046287784353e-05,
    -0.00017122927238233387,
    -0.008795296773314476,
    0.009200588800013065,
    -0.006785948295146227,
    0.028271257877349854,
    0.018931765109300613,
    0.016355399042367935,
  ],
  'This makes me so angry and frustrated': [
    0.183515265583992,
    -0.029108818620443344,
    -0.018940437585115433,
    0.16955099999904633,
    -0.07135626673698425,
    0.06460697203874588,
    -0.07893148809671402,
    0.07514217495918274,
    0.12172309309244156,
    0.19083626568317413,
  ],
  'I feel nothing today': [
    0.05742885544896126,
    0.009276262484490871,
    -0.015289772301912308,
    0.0009941915050148964,
    -0.021609734743833542,
    0.0006966697983443737,
    -0.013212052173912525,
    0.02216663956642151,
    0.01846163347363472,
    0.009984776377677917,
  ],
  'Today was a great day and I felt wonderful': [
    0.1542942374944687,
    -0.04961022734642029,
    -0.021712662652134895,
    -0.05428064987063408,
    -0.030411895364522934,
    0.10285940766334534,
    0.007325266487896442,
    -0.05982472002506256,
    0.03139490261673927,
    0.12544764578342438,
  ],
  'The quick brown fox jumped over the lazy dog': [
    0.24373970925807953,
    -0.10785162448883057,
    -0.12546607851982117,
    -0.07246184349060059,
    0.3709394037723541,
    -0.08498900383710861,
    -0.03576260060071945,
    -0.15480954945087433,
    -0.06720925122499466,
    -0.06736700236797333,
  ],
  'I am so sad and heartbroken': [
    0.14323167502880096,
    -0.0042037880048155785,
    -0.006477745249867439,
    0.0019004767527803779,
    -0.05492603778839111,
    0.030431291088461876,
    -0.027710849419236183,
    0.024354755878448486,
    0.049799833446741104,
    0.10380487889051437,
  ],
  'Wow that was surprising and unexpected': [
    0.17926029860973358,
    -0.0542730875313282,
    -0.04211649298667908,
    -0.08582140505313873,
    -0.08704036474227905,
    0.14770174026489258,
    0.31680700182914734,
    -0.0788261815905571,
    0.019036270678043365,
    0.16704733669757843,
  ],
};

// ── Helpers ────────────────────────────────────────────────────────────────

/// Absolute tolerance for float32 comparison.
///
/// The Python pipeline operates in float64 internally but exports assets as
/// float32.  The Dart implementation accumulates float32 rounding errors across
/// ~200 dot-product terms.  2e-4 is generous enough to cover this while still
/// catching real bugs.
const double _kAbsTol = 2e-4;

/// Relative tolerance (used for values whose magnitude exceeds 0.01).
const double _kRelTol = 0.01; // 1%

void _expectClose(double dart, double python, String context) {
  final absDiff = (dart - python).abs();
  final relDiff = python.abs() > 1e-6 ? absDiff / python.abs() : absDiff;
  if (absDiff > _kAbsTol && relDiff > _kRelTol) {
    fail('$context: dart=$dart python=$python '
        'absDiff=${absDiff.toStringAsExponential(2)} '
        'relDiff=${(relDiff * 100).toStringAsFixed(2)}%');
  }
}

// ── Tests ──────────────────────────────────────────────────────────────────

void main() {
  // Required to load Flutter assets (rootBundle) in tests.
  TestWidgetsFlutterBinding.ensureInitialized();

  late Vectorizer vectorizer;

  setUpAll(() async {
    vectorizer = Vectorizer();
    await vectorizer.load();
  });

  group('Vectorizer.transform — output matches Python reference', () {
    for (final entry in _kRefVectors.entries) {
      final sentence = entry.key;
      final refFirst10 = entry.value;

      test(sentence, () {
        final result = vectorizer.transform(sentence);

        expect(result.length, equals(200),
            reason: 'Output must have exactly 200 dimensions (LSA components)');

        // Compare first 10 dimensions against Python reference.
        for (int i = 0; i < refFirst10.length; i++) {
          _expectClose(
            result[i].toDouble(),
            refFirst10[i],
            'dim[$i] for "$sentence"',
          );
        }
      });
    }
  });

  group('Vectorizer.transform — output is L2-normalised', () {
    for (final sentence in _kRefVectors.keys) {
      test(sentence, () {
        final result = vectorizer.transform(sentence);
        double norm = 0;
        for (final v in result) {
          norm += v * v;
        }
        norm = math.sqrt(norm);
        expect(norm, closeTo(1.0, 5e-4),
            reason: 'Output vector must be unit-length (L2 norm ≈ 1)');
      });
    }
  });

  group('Vectorizer.transform — deterministic (same input → same output)', () {
    for (final sentence in _kRefVectors.keys) {
      test(sentence, () {
        final a = vectorizer.transform(sentence);
        final b = vectorizer.transform(sentence);
        for (int i = 0; i < a.length; i++) {
          expect(a[i], equals(b[i]),
              reason: 'transform() must be deterministic (dim $i differs)');
        }
      });
    }
  });

  group('Vectorizer.transform — empty / OOV input', () {
    test('empty string returns zero vector or unit vector', () {
      // Empty input: all counts are 0, tfidf is all-zero → L2 norm guard returns
      // zero vector before SVD.  Final output is either all-zero or unit-length
      // depending on whether SVD output also happens to be zero.
      final result = vectorizer.transform('');
      expect(result.length, equals(200));
      // Should not throw and should produce finite values.
      for (final v in result) {
        expect(v.isFinite, isTrue, reason: 'All values must be finite');
      }
    });

    test('out-of-vocabulary tokens produce non-NaN output', () {
      // Tokens not in vocab are skipped; result is zero → guard handles it.
      final result = vectorizer.transform('xyzzy qqqqqq aaabbbccc');
      expect(result.length, equals(200));
      for (final v in result) {
        expect(v.isNaN, isFalse, reason: 'NaN values are not allowed');
        expect(v.isInfinite, isFalse, reason: 'Infinite values are not allowed');
      }
    });

    test('single character tokens are ignored (min length 2)', () {
      // "a b c" — all single-char tokens should be skipped.
      final allSingleChar = vectorizer.transform('a b c');
      final empty = vectorizer.transform('');
      // Both should produce identical output since no vocab terms match.
      for (int i = 0; i < 200; i++) {
        expect(allSingleChar[i], equals(empty[i]),
            reason: 'Single-char tokens must be filtered out (dim $i)');
      }
    });
  });

  group('Vectorizer.transform — case insensitivity', () {
    test('upper/lower/mixed case produce the same result', () {
      final lower = vectorizer.transform('i am happy');
      final upper = vectorizer.transform('I AM HAPPY');
      final mixed = vectorizer.transform('I Am Happy');
      for (int i = 0; i < 200; i++) {
        expect(lower[i], equals(upper[i]),
            reason: 'lower vs upper: dim $i differs');
        expect(lower[i], equals(mixed[i]),
            reason: 'lower vs mixed: dim $i differs');
      }
    });
  });
}
